version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/galaxy
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
